### ISSUE TITLE
Doesn't work on MCC Island

### ISSUE THREAD

**Issue by AwesomeKalin** [emilyy-dev/bypass-resource-pack#2]
MCC Island uses a custom resource pack. However it still asks you to use a resource pack and pressing yes still downloads and enables the resource pack. Am I using it wrong or is it a bug?

**Comment by clrxbl** [comment]
works fine, have used it a countless times on MCCI

**Comment by NoahvdAa** [comment]
> and pressing yes still downloads and enables the resource pack. Am I using it wrong or is it a bug?

<img width="758" alt="image" src="https://user-images.githubusercontent.com/44026893/187913730-a0778cfb-3f15-4a29-9b6b-2b3509593a17.png">

Click the bypass button instead of proceed.

**Comment by emilyy-dev** [comment]
Make sure you've got the mod installed, if you keep having issues feel free to join my [discord server](https://discord.gg/Zk9HRuz4ZZ) for further assistance
